#!/bin/bash
PATH=/bin:/usr/bin

echo "// Autogenerated at `date`"
echo "// DO NOT MANUALLY EDIT THIS FILE"
echo

for f in $*; do
	echo "#include \"$f\""
done
echo

echo "int main(int argc, char *argv[])"
echo -n "{"

for f in $*; do
	className=`basename $f .hpp`
	echo
	echo "    $className test_$className;"
	echo "    QTest::qExec(&test_$className, argc, argv);"
done

echo "}"
